-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial,
    user_name character varying(20) NOT NULL,
    user_surname character varying(20) NOT NULL,
    user_fathername character varying(20),
    phone character varying(20) NOT NULL,
    PRIMARY KEY (user_id),
    CONSTRAINT "UnPhone" UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id serial,
    product_name character varying(100) NOT NULL,
    product_description text,
    product_price numeric(10, 2) NOT NULL,
    product_count integer NOT NULL,
    category_id integer NOT NULL,
    PRIMARY KEY (product_id),
    CONSTRAINT "UnName" UNIQUE (product_name)
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id serial,
    category_name character varying(20) NOT NULL,
    category_description text,
    PRIMARY KEY (category_id),
    CONSTRAINT "UnCategory" UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.address
(
    address_id serial,
    user_id integer NOT NULL,
    city character varying(50) NOT NULL,
    street character varying(100) NOT NULL,
    postal_code character varying(5) NOT NULL,
    PRIMARY KEY (address_id),
    CONSTRAINT "UnAdress" UNIQUE (user_id, city, street, postal_code)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    order_id serial,
    user_id integer NOT NULL,
    address_id integer NOT NULL,
    product_id integer NOT NULL,
    order_count integer NOT NULL,
    PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public.product
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.address
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (address_id)
    REFERENCES public.address (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;